### ISSUE TITLE
Make Detailed National Modelling "hidden"

### ISSUE THREAD

**Issue by OmNomNomzzz** [ConclusionNL/global-mitigation-potential-atlas#100]
We need to only allow some users to access the "detailed national modelling" as it may be too confusing for regular users. We either need this behind a password/ special key press, or non-obvious "easter egg" button. Whatever is easiest.

This is the Mitigation Potential Diagram (stacked graph with bar chart underneath). For example SG and MY in the following:
![image](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/23158406/56810ae4-bb62-4879-b2bd-a22119255ffd)

Again, it does not matter how this is done. This is a critical functional requirement that we have only found out after showing this to stakeholders so it is a high priority that we would not have anticipated before.

**Comment by lucasjellema** [comment]
Behind a password is quite complex. That is a not an approach to follow. A special key combination is ok.

Should this special key combination be used only once per session to unlock this (and other?) advanced features for the duration of the session?

**Comment by lucasjellema** [comment]
Implementation:
with the mouse hovering over the stacked area chart, press CTRL+Shift+Y. This will turn on a show advanced options mode that will be active for the duration of the session. While in this mode, the detailed national modelling is visible.

![image](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/1296324/cb857842-e82c-484a-8b91-aa39e27daf07)

**Comment by OmNomNomzzz** [comment]
The issue is not working on the "a" or "t" versions of the website. I still see detailed modelling results:

![image](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/23158406/a6abeb78-7a80-4187-bea6-1b12b04ae904)

The feature described would be perfect when implemented. I will review and close issue once implemented.

**Comment by OmNomNomzzz** [comment]
Feature has been successfully implemented. Placing the mouse over the chart and pressing Ctrl+Shift+Y toggles it on and off.
