### ISSUE TITLE
Add additional radio-button to heatmap

### ISSUE THREAD

**Issue by OmNomNomzzz** [ConclusionNL/global-mitigation-potential-atlas#101]
After additional discussions with the policy team and the stakeholders. We were able to get some use out of the "Mitigation Cost". But only for the heatmap, not for the subsequent parts.

I.e. we need another radio button below the existing ones on the heatmap. This should be labeled "Average Mitigation Cost to Reach Net Zero ($/tCO2e)"
![image](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/23158406/859645bc-ee04-4d1a-948e-06f95fbe3fba)

This will also be additional information displayed when users click a country. 
This should be in the following format: "Mitigation Cost to Reach Net Zero          xx $/tCO2e"

![image](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/23158406/9f5b4aa6-9869-49c3-acf3-6f59e1510287)

Note that this does not need to be updated in any other place. like collaboration, etc.

I have added a column to heatmap_collaboration.csv file. It looks like the following:
![image](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/23158406/f39b3d24-ff61-4c29-a2c1-7ada8776165c)

I have uploaded the file with added column name in box: Portal development -> Modelling Content Ready for Upload -> Test Data For Website -> heatmap_collaboration.csv
https://climateanalytics.box.com/s/m8l1f9is5ugb07taimnemhg5i9ml6o9f

This is related to Issue #99 .

**Comment by lucasjellema** [comment]
The label you propose seems quite long:
Average Mitigation Cost to Reach Net Zero ($/tCO2e)

it will cause layout issues in both places. Can you suggest something shorter?

Note: when on collaboration mode and multiple countries are selected - how should we derive the heatmap value for the selected countries for this new property? #61 was implemented but now needs to be amended because of this new property

**Comment by lucasjellema** [comment]
two issues with the values:
* there is no value for Singapore
* the values have a large number of digits; are you certain they should be  included?
![image](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/1296324/c2c014fd-16e0-4f3e-bf9a-6177244384c3)

**Comment by lucasjellema** [comment]
The additional option and property are added.

**Comment by OmNomNomzzz** [comment]
Additional property implementation works as intended.

Label too long:
The label name can be shortened to "Net Zero Mitigation Cost ($/tCO2e)"

What to do in international collaboration mode:
This value will not be displayed in international collaboration mode. So do not change the international collaboration algorithm. I see that it is not implemented in international collaboration mode. This is as intended. We are still unable to figure out how to deal with the value in international collaboration mode. The old issue still stands unsolved. I.e. we DO NOT need it in the following locations:
![image](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/23158406/0b0475d8-ae46-4cca-9693-e3f7f7e85c1d)
![image](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/23158406/2e929b6a-6f47-429f-9305-f1627c323531)

How to deal with issue #61 
You do not need to change the logic. You still read the respective number from the collaboration, just like for the mitigation potential. So for the file attached, ID would be 24.2 $/tCOe2, SG will have no value. SG+ID would be 17.9 $/tCO2e.

Singapore does now have a value:
Sorry, I forgot to add this detail. Some countries will not have a value as they cannot reach net zero. I have current set them as "". They should be grayed out, perhaps the same a the countries not in the heatmap.csv file. This was an issue we faced earlier on when this was removed. We did not know if it was politically sensitive to say this. However, it was determined that itshould solved by not having a value for some countries. When you click a country (only SG in this case), it currently says "NaN". I do not know what it should say. I need to get feedback. So it is ok to leave it as is.

Large digits:
I shall raise a new issue to handle all digits on the platform. It will be clearer.

**Comment by lucasjellema** [comment]
I cannot find a file that has a value for Singapore and where the column names are aligned with 10,20 and 50. Please let me know where to find it.

**Comment by OmNomNomzzz** [comment]
Added issue to deal with number of digits #103

**Comment by OmNomNomzzz** [comment]
![image](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/23158406/09a3d17d-e330-4719-aca4-91788a4369f7)
https://climateanalytics.box.com/s/b562mutvcyq9dpjermwekcdu2xkx4qf1

Should now have the values for Singapore for 0, 10, 20, 50. But it will not have any values for "Mitigation Cost".

**Comment by OmNomNomzzz** [comment]
The website now has the correct labels. It also now takes in files with the corresponding label for 0, 10, 20, 50. This issue has been resolved.
