### ISSUE TITLE
Number of digits to display

### ISSUE THREAD

**Issue by OmNomNomzzz** [ConclusionNL/global-mitigation-potential-atlas#103]
There are a few places where the number of digits are too high. We need a standard logic and process for handling digits.

After trying a few methods, it is easiest if this is decided by me but handled by front end team. All data from the modelling team will have a lot of decimal places as if we round it off first, it will lead to strange results in the plotting. This is my suggestion.

I will add the general logic and list the places on the website where numbers are displayed that need to be handled by front-end team.

Logic:

If number < 1000:
    Use three significant figures for all numbers on the website. Round off (i.e. higher if next number is more than or equal to 5).
else;
    Use 0 decimal place.

E.g. 
0.231243 -> 0.231
1.125234  -> 1.13
1.32254 -> 1.32
12.377254 -> 12.4
582.234995 -> 582
1827.22394 -> 1827
12847.3002 -> 12847

Places where large numbers may be seen.
![image](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/23158406/4b55055a-ed55-436f-ac54-a492039a0831)

![image](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/23158406/0cb09174-3e43-4354-bc3d-18057019025e)

![image](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/23158406/1a42e7db-8fbe-46e7-b9e5-5fc4bde5b946)

**Comment by Quintin-Yu** [comment]
![image](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/36072659/d12d7e9f-59dc-4f65-ba09-d564c619d216)
Country card has been rounded

**Comment by Quintin-Yu** [comment]
![image](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/36072659/b9654928-f967-4169-b406-4d1d8c3a7736)
Gauze rounding

**Comment by Quintin-Yu** [comment]
Rounding has been applied to all the items requested based on screenshots. Please review the changes.

**Comment by OmNomNomzzz** [comment]
The number of digits issue has been resolved well.
