### ISSUE TITLE
Update csv data for website

### ISSUE THREAD

**Issue by OmNomNomzzz** [ConclusionNL/global-mitigation-potential-atlas#104]
There were modelling updates. This created a few GitHub issues. These issues have been resolved related to labelling etc. We now need to update the modelling results on the website.

This needs to be done so that we can get proper feedback on the results from users in the next few days. 

Need to update the csv inputs for the website from the values in box. Portal development -> Modelling Content Ready for Upload

https://climateanalytics.box.com/s/khkh78fmg1e276qdzu5slh9c6vnehgne

Note we will need to update the modelling results again once or twice again in the next few days (including one last time before the big website freeze). I will create individual issues each time results need to be updated again like this.

**Comment by lucasjellema** [comment]
I went to the Box folder and downloaded these files:
![image](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/1296324/c78ba58c-c8b8-4b87-810a-829bcd354e0f)
These have now been committed

**Comment by OmNomNomzzz** [comment]
Values have been updated properly.  Thank you! I shall close this issue. I will open a new one issue if the data needs to be updated again.
