### ISSUE TITLE
Unbrace: cases

### ISSUE THREAD

**Issue by noni-12** [ConclusionNL/global-mitigation-potential-atlas#106]
Is it possible to select multiple options under target group in the case policy information?

<img width="793" alt="Screenshot 2023-11-22 at 11 10 58 am" src="https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/150308465/49a8b870-2b35-4e76-9800-c4ebd4c6852d">

**Comment by Quintin-Yu** [comment]
![image](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/36072659/a1a334a3-e6ab-4006-b162-f7f5da649f30)
Can now select multiple Target Groups.
- To select one use only click
- To select multiple use ctrl + click

**Comment by Quintin-Yu** [comment]
Updated the Accept environment with these changes as well. Shouldn't be done until the review has been done technically but considering this is a high priority for editting on your side I updated it right away.

**Comment by noni-12** [comment]
Thanks, working fine
