### ISSUE TITLE
Cases

### ISSUE THREAD

**Issue by noni-12** [ConclusionNL/global-mitigation-potential-atlas#107]
Is it possible to add only year, not months and dates in the start and end date of the policy in the case studies?

![Uploading Screenshot 2023-11-22 at 11.30.46 am.png…]()

**Comment by Quintin-Yu** [comment]
![image](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/36072659/094bf7c2-fe97-459b-8e3f-bffd34f98cc2)
Removed day and month from the start date and end date

**Comment by Quintin-Yu** [comment]
Updated the Accept environment with these changes as well. Shouldn't be done until the review has been done technically but considering this is a high priority for editting on your side I updated it right away.

**Comment by noni-12** [comment]
All good, thanks
