### ISSUE TITLE
Rounding off number when mouse over countries

### ISSUE THREAD

**Issue by OmNomNomzzz** [ConclusionNL/global-mitigation-potential-atlas#117]
When the mouse pointer hovers over a country, a display comes up with Net Zero mitigation cost for that country, the values here are not yet rounded, can it be displayed with one decimal point figure as in the box once the country is clicked

![image](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/23158406/855fd495-70cf-43de-a403-674dd6529ec0)

This should be 3 significant figures. This is related to #103 .

**Comment by lucasjellema** [comment]
Implemented
![image](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/1296324/8f930328-c135-410c-8534-5f5a10eed8d7)

**Comment by OmNomNomzzz** [comment]
Issue has been resolved in the "t" version of the website successfully.
