### ISSUE TITLE
Change name of "Mitigation Potential Diagram" to "Dynamic Pareto Abatement Cost Curve"

### ISSUE THREAD

**Issue by OmNomNomzzz** [ConclusionNL/global-mitigation-potential-atlas#118]
The official name of the dyamic diagram is now: Dynamic Pareto Abatement Cost Curve (D-PACC, or D-PAC Curve). This sounds similar to the usual "MAC Curve" (Marginal Abatement Cost Curve). This is the first time someone has ever made D-PACC by the way.

The "dynamic" version,, D-PAC Curve, is technically the one that you all have just made with the sliders. The version without the sliders is what we now offically named the PAC Curve.

![image](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/23158406/4cfdae0c-a626-4efd-9188-5b554619fb2b)

Please change the "Mitigation Potential Diagram" to "Dynamic Pareto Abatement Cost Curve". If the name is too long, then use "Pareto Abatement Cost Curve"

![image](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/23158406/b8874285-6465-4b2b-bb47-8cf5edee2e0a)

Please change "Show Mitigation Potential Diagram" to "Show Dynamic Pareto Abatement Cost Curve". It is ok for it to be two line. If it is too complicated to deal with the long text, use "Dynamic Pareto Abatement Cost Curve", or just "Pareto Abatement Cost Curve". Do whatever is easiest, either option is good enough.

**Comment by lucasjellema** [comment]
Implemented:
![image](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/1296324/ee5c3640-e2a8-4aef-8ec8-7296018a8b8d)
and
![image](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/1296324/412adc24-3681-46b0-8ee8-d80b34e0d3cf)

**Comment by OmNomNomzzz** [comment]
Sorry, I just realized that we also need to change the name on the actual curve.

![image](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/23158406/20932dcf-e5a7-4150-a37d-8f9bdda328d4)


The name should be changed to "Country's Dynamic Pareto Abatement Cost (D-PAC) Curve for 2050"

**Comment by lucasjellema** [comment]
implemented:
![image](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/1296324/36994ec2-19a2-42a1-8f9d-f49bdb7549ef)

**Comment by OmNomNomzzz** [comment]
Everything has been implemented. Thank you!
