### ISSUE TITLE
Numbers for additional mitigation potential from collaboration should be forced to non-negative.

### ISSUE THREAD

**Issue by OmNomNomzzz** [ConclusionNL/global-mitigation-potential-atlas#119]
When addition countries to the collaboration, the benefits are calculated by taking the difference of the mitigation potential before and after collaboration. See below:

![image](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/23158406/2da8394f-d909-4fea-8517-2cf5582f18c2)

This is currently being calculated on your end. Please also add the following algorithm:

additional mitigtion potential from adding country = x
if x <0:
          set x = 0
else:
          continue

So the number in the screenshot above should be "0" instead of "-1.6".

We have looked at this issue throughly and it arises from the way some post processing is done. In short, it is a ronuding error. Current process to deal with properly will be very manual and time consuming. Rest assured, there is no issue with the fundamental results and the D-PAC Curve. This is something we will deal with properly in the next phase on the modelling side.

**Comment by lucasjellema** [comment]
Implemented:

![image](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/1296324/7345407f-f020-4660-ac37-a272814ae244)

when the value < 0, then 0 is presented. (it feels a little bit like cheating)

**Comment by OmNomNomzzz** [comment]
It is a bit of cheating. If anything, the 0 is still an underestimation of the benefits, but it is a better lower bound than negative. In general, the values on this page are an underestimation of the benefits. Let me try to make a simple sketch to show why this has happened.

![image](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/23158406/17bda89d-1025-4ada-9639-8db708b7d960)

We need to project a line from the initial (BAU point x) to the line. And the mitigation potential is x2-x1. Gradient = (y2-y1)/(x1-x2) is the "mitigation potetential at 0/10/20/50 $/tCO2e". However, we have only sampled the data on the line at certain intervals, the big dots on the line. So the closest value is not x2, but x3. So the plot shows x3. The main output is the line. And if actually look at the PAC Curve lines before and after collaboration, we would see that the collaboration line is always below the non-collaboration line. So the fundamental results is ok, but the way we are sampling and plotting underestimates the benefits, sometimes even makes it negative. However, we do know that the lower bound has to be zero.

![image](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/23158406/5a1be808-3209-4fcc-8384-73e1fb3d53d5)


Consider the top line (without collaboration), and the bottom line (with collaboration). The collaboration is always cheaper than without collaboration. The dotted line cuts the top line at x4, and the bottom line at x2. So ideally, the mitigation potential for the bottom line is higher (lower emissions = higher mitigation). However, because the data for the plotting is only in the big dots on the line, the closes data for the bottom line is x3. Now x3 is in fact larger than x4, so it has lower mitigation potential. So the system will think that the mitigation potential is lower for the bottom line, which is incorrect. We at least know that the x2 is lower than or equal to x4. So the mitigation potential should be at least zero. That is what we are doing by "cheating" and setting the new lower bound. Ideally we need a systematic way of finding more accurate values for x2, i.e. make sure x3 is as close to x2 as possible. But that is for the next phase.

**Comment by OmNomNomzzz** [comment]
Having said that, the issue has been resolved on the "t" version of the website so I shall close the issue.
