### ISSUE TITLE
Update csv data for website with new asset names

### ISSUE THREAD

**Issue by OmNomNomzzz** [ConclusionNL/global-mitigation-potential-atlas#120]
The total_data_autarky.csv and total_data_collaboration.csv files now have human readable technology names.

![image](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/23158406/8d3a5cb2-8062-4012-b7a8-858627086792)

Please update the csv files on website so that we can take new screenshots with the different names for the writeups.

**Comment by OmNomNomzzz** [comment]
Files are in box: portal development -> Modelling content ready for upload
https://climateanalytics.box.com/s/khkh78fmg1e276qdzu5slh9c6vnehgne

**Comment by lucasjellema** [comment]
implemented

**Comment by OmNomNomzzz** [comment]
Implemented in "t" version of website.
