### ISSUE TITLE
Update Labels and Titles of figures

### ISSUE THREAD

**Issue by OmNomNomzzz** [ConclusionNL/global-mitigation-potential-atlas#121]
The titles for three figures need to be updated. Please implement as much as possible. If some changes require "new features", i.e. too much work, please try to find a different way to present the information. Other methods are welcome. Please let me know if any of these changes are too much work and cannot even be done,

1.
![image](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/23158406/4d9c9213-6d2f-4e7a-ad5d-135c3757fd68)
The legend on the map needs to be updated so that the top is called "Annual Mitigation Potential (MtCO2e) at Additional Average Abatement Cost Compared to Current Energy Mix of:"
The first legend label should be changed from "0 $/tCO2e" to "Net Zero Additional Cost"
The last legend label should be changed from "Net Zero Mitigation Cost ($/tCO2e)" to "Additional Average Abatement Cost to Reach Net Zero Emissions ( $/tCO2e)"
I know this is very long, but it is ok if it goes to 2-3 lines. It is more imporant right now to be accurate and minimize confusion for the reader.

2.
![image](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/23158406/eff13caf-8045-4777-a3b1-414f4b3b196e)
The top portion should not match the legend on the map.
Please add a title before the PAC Curve that reads, "Pareto Abatement Cost (PAC) Curve: Trade-off between emissions and costs to build a new system in 2050.

3.
![image](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/23158406/efe5a6a6-b176-48bd-995f-deaf3fa2ccb8)
Please change the title of the graph. This is related to Issue #118.
Please also add title in between the two graphs labeled: "Assets in Cost-Optimal Technology Mix"
Add label to x-axes of bar chart: "Asset Name"
Add label to y-axes of bar chart: "Asset Costs (Billion $)"

**Comment by lucasjellema** [comment]
implemented 1 and 2

![image](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/1296324/947ca8f8-6583-4614-bf33-3220492d3889)

![image](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/1296324/2f083cb7-8545-45ab-a542-1488cea54a4e)

**Comment by lucasjellema** [comment]
@OmNomNomzzz  overhead you write "The top portion should not match the legend on the map." I am not sure I understand this statement - especially the word _not_. Should it be _now_ perhaps? Please clarify

**Comment by OmNomNomzzz** [comment]
Hi @lucasjellema  that was a typo. It should be "NOW" match. Sorry for the confusion.

1 and 2 are implemented as intended. Thank you.

**Comment by lucasjellema** [comment]
implemented 3.
![image](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/1296324/28e80a11-cc13-463b-a180-6195615c31e6)

@OmNomNomzzz please indicate what - if anything - should change. Perhaps position of the axis-labels? I am not sure what works best.

**Comment by OmNomNomzzz** [comment]
Hi @lucasjellema  I think this all works well. The overall size of the pop-up is still good.

I just did a final check and realized there was a typo.

![image](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/23158406/f7336c87-fe96-44fc-b466-3eb873db2137)
Please change "Annual Mitigation Potential (MtCO2e) at Average Abatement Cost of" to "Annual Mitigation Potential (MtCO2e) at Additional Average Abatement Cost of". We are missing the word "Additional".

Similarly.
![image](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/23158406/43b7c31b-38e6-4f92-a2f7-5d9c24c1630b)
Please change "Annual Mitigation Potential (MtCO2e) at Average Abatement Cost of" to "Annual Mitigation Potential (MtCO2e) at Additional Average Abatement Cost of". We are missing the word "Additional".

**Comment by lucasjellema** [comment]
like this?
![image](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/1296324/125d9381-261d-4367-ac89-258f1d6fba39)

**Comment by OmNomNomzzz** [comment]
Yes, this works well. The requested changes have been made. I shall close the issue. Thank you!
