### ISSUE TITLE
Final update of CSV files to include more collaborations

### ISSUE THREAD

**Issue by OmNomNomzzz** [ConclusionNL/global-mitigation-potential-atlas#125]
Data for collaboration for the last four countries have been added. The files have been updated on box.
https://climateanalytics.box.com/s/khkh78fmg1e276qdzu5slh9c6vnehgne

Please update all modelling csv files from box to the portal. This should ideally be the final update of CSV files.

The format of the should be the same. It should just have collaborations for VN, TH, LA, KH (and all subsets) now.

**Comment by lucasjellema** [comment]
I have updated the files, committed the change which kicked off the pipeline to refresh the T environment.

![image](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/1296324/3f8be91f-380c-42c6-8f0b-7583a0b6507a)

**Comment by lucasjellema** [comment]
![image](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/1296324/74ce48cd-9be6-448a-8d25-05d1c5633fda)
These were the versions uploaded

**Comment by OmNomNomzzz** [comment]
The values have been updated on the "t" website successfully. Thank you. I shall close the issue.
