### ISSUE TITLE
Update CSV data on website (previous missing data)

### ISSUE THREAD

**Issue by OmNomNomzzz** [ConclusionNL/global-mitigation-potential-atlas#126]
The previous update was missing data for the VN-LA-KH collaboration. And that was causing some issues with the collaboration pop-up. E.g. if you try clicking VN, and then LA for collaboration.

The data for the collaboration has been added now in box. Please update the csv files from box to the website.

**Comment by lucasjellema** [comment]
updated datafiles were uploaded and committed

**Comment by OmNomNomzzz** [comment]
The data has been updated. The portal now works as intended for the collaboration of last four countries. Thank you!
