### ISSUE TITLE
Contact us

### ISSUE THREAD

**Issue by noni-12** [ConclusionNL/global-mitigation-potential-atlas#128]
Update all contact information as " For additional information, please contact the GMPA consortium at info@mitigationatlas.org"

**Comment by lucasjellema** [comment]
@noni-12  can you indicate which pages in the webapplication should be updated?

**Comment by noni-12** [comment]
start year is working fine now.
Valid till which was earlier default showing as 'on going' in case of no input is no longer working.
Please add valid till as 'on going' in case of no input for all countries for climate strategies and policy inventory
<img width="663" alt="Screenshot 2023-11-27 at 5 57 49 pm" src="https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/150308465/11934601-f517-431e-ad63-d4072f2a1a7d">

**Comment by lucasjellema** [comment]
Hi @noni-12  - could it be that your comment is actually for #127 ?

**Comment by lucasjellema** [comment]
I guess this one needs to be updated?
![image](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/1296324/2fc2dad6-74e0-4322-8a59-cd96baea2ba1)

**Comment by lucasjellema** [comment]
Is this the change as required:
![image](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/1296324/062471fb-43a8-450a-980e-ca0906ccb69a)

do more changes have to be made? @noni-12

**Comment by Quintin-Yu** [comment]
@lucasjellema Pretty sure this is about the country page contact details I am changing them now as I am typing this

**Comment by lucasjellema** [comment]
> @lucasjellema Pretty sure this is about the country page contact details I am changing them now as I am typing this

okay. then should I reverse my change? The issue is not quite clear to me.

**Comment by Quintin-Yu** [comment]
> > @lucasjellema Pretty sure this is about the country page contact details I am changing them now as I am typing this
> 
> okay. then should I reverse my change? The issue is not quite clear to me.

Yes, the intro card text I got from Clare, I think that should stay as is

**Comment by lucasjellema** [comment]
I will try to not start working on issue too eagerly as long as it is not entirely clear what the issue entails.

**Comment by noni-12** [comment]
Looks good, can it be added at the end of country pages also?
![Screenshot 2023-11-27 at 6 33 57 pm](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/150308465/4caacc90-4296-4528-a3b5-952d177653ab)

**Comment by Quintin-Yu** [comment]
This change has been applied to the test environment, not the accept

**Comment by noni-12** [comment]
Looks good, thanks
