### ISSUE TITLE
Update title of legend of heatmap

### ISSUE THREAD

**Issue by OmNomNomzzz** [ConclusionNL/global-mitigation-potential-atlas#129]
Need to make the already very long legend of the heatmap longer because clarity is more important than looks.

![image](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/23158406/a6a95044-277d-4aa3-af2f-2ef4617968c8)
Please change the "Annual Mitigation Potential (MtCO2e) at Additional Average Abatement Cost of:" to "Annual Mitigation Potential (MtCO2e) at Additional Average Abatement Cost (Compared to Current Energy Mix) of:"

Please also change the "Additional Average Abatement Cost to Reach Net Zero Emissions ($ /tCO2e)" to "Additional Average Abatement Cost (Compared to Current Energy Mix) to Reach Net Zero Emissions ($ /tCO2e)"

![image](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/23158406/2faab9ec-f34d-4adb-9880-b7407bb61162)

Please also change the "Annual Mitigation Potential (MtCO2e) at Additional Average Abatement Cost of:" to "Annual Mitigation Potential (MtCO2e) at Additional Average Abatement Cost (Compared to Current Energy Mix) of:"

Please also change the "Additional Average Abatement Cost to Reach Net Zero Emissions ($ /tCO2e)" to "Additional Average Abatement Cost (Compared to Current Energy Mix) to Reach Net Zero Emissions ($ /tCO2e)"

**Comment by lucasjellema** [comment]
It will look like this.
![image](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/1296324/304afeca-c2d4-4187-a2a6-81eb4d208db0)

**Comment by OmNomNomzzz** [comment]
Yes that works. Thank you!!
