### ISSUE TITLE
Case study section in the country page

### ISSUE THREAD

**Issue by noni-12** [ConclusionNL/global-mitigation-potential-atlas#131]
Hyperlinks of the case study sectors in the country pages are not working for Singapore, Malaysia, Philippines, Thailand. I am not if there is still chance to correct it. If yes then please do it least for Singapore page.
 
![Screenshot 2023-11-29 at 4 03 51 pm](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/150308465/b79cf6ab-99b2-431d-a07d-8467e0aaa323)

**Comment by lucasjellema** [comment]
@Quintin-Yu  can you take a look urgently ?

**Comment by Quintin-Yu** [comment]
This issue has been dealt with.

**Comment by noni-12** [comment]
working fine, thank you
