### ISSUE TITLE
BE - Case Study overview (L)

### ISSUE THREAD

**Issue by Quintin-Yu** [ConclusionNL/global-mitigation-potential-atlas#21]
~~This page can be accessed through #14 By clicking on a bar in the bar chart or by clicking on the technology in the country page
- Display cases from the country the original page is from
- Display cases from the Technology that was selected on the original page
~~

**Comment by lucasjellema** [comment]
I do not quite understand what needs to be done here.

Clicking on the bar chart does not result in any navigation.

What is an example of navigating to technology-specific cases?

**Comment by Quintin-Yu** [comment]
Those items were requested in the original concept of the website. But those have now been changed.

Cases should not be grouped by country but grouped by continent, this will not be done through the bar chart.
Navigation to the cases through the Technology is also not possible with the current files as it is not clear what belongs to which sector. The sectors being:
1. Power
2. Energy
3. Transport
4. Agriculture
5. Industry
