### ISSUE TITLE
General - Provide CA tools to work

### ISSUE THREAD

**Issue by xavierroosendaal** [ConclusionNL/global-mitigation-potential-atlas#26]
We want to enable CA to edit content as this is their wish and it would save us time. However, they have no idea how to do that. A short workshop should be done in order to explain it to them.

- [x] Plan workshop 
- [x] Share any information or access needed
- [x] Do and record workshop

**Comment by Quintin-Yu** [comment]
Workshop will still be done as planned, but CA might not be able to upload content after the tenth. Before they can I will be available to upload content when it is needed

**Comment by Quintin-Yu** [comment]
Workshop has been done and finished
