### ISSUE TITLE
Derive data from files for horizontal gauge Cost of achieving maximum mitigation potential in autarky vs collaboration 

### ISSUE THREAD

**Issue by lucasjellema** [ConclusionNL/global-mitigation-potential-atlas#36]
The data presented in the horizontal level gauge - see below - is currently static (hard coded). We need data and instructions from Aniq in order to use the proper data. When the data is available, it needs to be associated with this gauge.

![image](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/1296324/3b99fe52-649d-4407-b8aa-b082ae61ba41)

**Comment by lucasjellema** [comment]
Here is how the values are derived:

for mitigation potential
![Image](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/1296324/20fbca40-06f9-4efa-aa0a-fae11006a50d)

and for costs:


![Image](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/1296324/f1e4a087-aafb-49fd-89a4-00d75d82be0c)

**Comment by lucasjellema** [comment]
based on real data files:



![Image](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/1296324/65b2d7b5-81bd-4f86-bae1-7820ab231b51)

**Comment by Quintin-Yu** [comment]
Feature seems completed and working as intended
