### ISSUE TITLE
Show benefits for country in collaboration suggestions

### ISSUE THREAD

**Issue by Quintin-Yu** [ConclusionNL/global-mitigation-potential-atlas#38]
In #11 the problem was raised that there needs to be data to show what the benefits are for a country to collaborate with another country. This should be shown like in the design below:
![image](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/36072659/4218eb38-e2a9-4b36-b24a-c49692c4e5c2)
Not that the Transport and Wind energy should be removed from the suggestion and instead be replaced with the absolute mitigation potential increase/decrease this country brings when collaborating.

**Comment by lucasjellema** [comment]
![image](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/1296324/c16b2cb7-5ff4-4a82-8fbe-b3d9be5a9025)

this is how the values can be derived: take the value for the collaboration between selected countries and candidate and subtract the value for the same set of countries in autarky (to make visible what collaboration can provide in extra benefit)

**Comment by lucasjellema** [comment]
Aniq slightly amended the requirement:

The logic will be as follows:

 

When going from SG -> SG+ID

Benefit = (SG+ID) – { (SG) + (ID) }

 

When going from SG+ID -> SG+ID+MY

Benefit = (SG+ID+MY)– { (SG+ID) + (MY) }

 

When going from SG+ID+MY -> SG+ID+MY+KH

Benefit = (SG+ID+MY+KH)– { (SG+ID+MY)+ (KH)}

 

So in general, when going from old collaboration -> new collaboration

Benefit = (New Collaboration)– { (Old Collaboration)+ (new country)}


![Image](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/1296324/554d296a-14ab-40ff-bdab-1df0e047bdac)



 

And you can get the data for all these from “heatmap_collaboration.csv”.

**Comment by lucasjellema** [comment]
I believe this issue is fixed.

![image](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/1296324/2a3863bb-0f7a-49ad-ae46-4a746d700eb1)

**Comment by Quintin-Yu** [comment]
Should numbers perhaps be limited to the second or third decimal to make the numbers look less big/more clear?

**Comment by OmNomNomzzz** [comment]
Will add a different ticket to describe how numbers should be rounded off in all parts of the website. The current implementation works well.
