### ISSUE TITLE
Favicon and (Tab) Title  should be customized to GMPA

### ISSUE THREAD

**Issue by lucasjellema** [ConclusionNL/global-mitigation-potential-atlas#47]
Currently the Tab running GMPA looks like this:
![image](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/1296324/274d7721-2acf-4ed2-b8d3-2f8adc4349b9)

- [x] The Umbraco icon must be replaced with the GMPA icon
- [x] The title of Home probably should be changed to GMPA

**Comment by Quintin-Yu** [comment]
![image](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/36072659/f9a70a71-7662-41fe-8aa2-6d28e2cbaebc)
![image](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/36072659/a9fd137d-aa6c-4855-b3a1-fe26092e9dd4)

FavIcon has been changed and the name of webpage have been changed as well See image. Umbraco FavIcon still flashes for a second before changing to correct Icon. This doesn't always happen.
