### ISSUE TITLE
One additional data set to display in Mitigation Potential Diagram (stacked area chart): sum in autarky

### ISSUE THREAD

**Issue by lucasjellema** [ConclusionNL/global-mitigation-potential-atlas#52]
Aniq has requested:

_I have now realized that compared to our previous conversation, we now have some “alternate” values to show when users click “show mitigation potential diagram”. I.e. the dropdown menu should have some more options.

For example if SG and ID are selected and users click “show mitigation potential diagram”. The dropdown menu should have:
1.	SG
2.	ID
3.	SG-ID (Full Collaboration)
4.	SG-ID (Autarky)

If SG, ID, and MY are selected. The dropdown menu should have:
1.	SG
2.	ID
3.	MY
4.	SG-ID-MY (Full Collaboration)
5.	SG-ID-MY (Autarky)

I hope this makes sense? I will have to modify the total_data file to add some more columns_ 

We already have all options except the final (Autarky) one. What we need to do:
* add an option to the select list for All Countries - Autarky (and change Full Collaboration to: All Countries - Collaboration)
![image](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/1296324/1e9a3ce4-bfe8-41e0-b502-0773bc586fa7)
* when the new Autarky option is selected, data from the total_data.csv file should be available that describes the autarky situation for the countrie-set

we wait for the data to be available (before implementing this feature)

**Comment by lucasjellema** [comment]
I have added support for autarky:


![Image](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/1296324/dbb6edec-cd9e-4700-86c2-4dbde3187315)


We make use of the newly provided data files and process these in an optimized way.

**Comment by Quintin-Yu** [comment]
Works as intended and functionality is reflected on the website. Issue can be closed.
