### ISSUE TITLE
Naming conventions of countries (S)

### ISSUE THREAD

**Issue by xavierroosendaal** [ConclusionNL/global-mitigation-potential-atlas#54]
It is a senstitive topic how we name countries. E.g. Vietnam is officially Viet Nam. We should check and change for the naming we use. It is proposed to use the UN list of https://www.un.org/dgacm/sites/www.un.org.dgacm/files/Documents_Protocol/officialnamesofcountries.pdf

- [x] Change Vietnam to Viet Nam
- [x] Change Laos/Lao PDR to Lao People's Democratic Republic

**Comment by lucasjellema** [comment]
I think this is done.
