### ISSUE TITLE
Add buttons to navigate to cases and policies in the side bar

### ISSUE THREAD

**Issue by RutgerdeValk** [ConclusionNL/global-mitigation-potential-atlas#60]
PO's have requested the return of the policy and cases button in de sidebar to quickly navigate to the overviews of these topics. 

![image](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/36072659/35dc1ee7-a56b-4858-bc12-55f9fffa10f3)
In the side nav as seen above add two buttons

- [ ] One named "Policies" that navigates to baseUrl/policies
- [ ] One named "Cases" that navigates to baseUrl/cases

**Comment by lucasjellema** [comment]
as far as I can tell, the buttons are there and do what they are supposed to do
