### ISSUE TITLE
Nice to have: When multiple countries are selected for collaboration, the world heat map colour should be based on their collaboration value instead of their individual values

### ISSUE THREAD

**Issue by RutgerdeValk** [ConclusionNL/global-mitigation-potential-atlas#61]

**Comment by lucasjellema** [comment]
this means:
* use collaboration value to determine heatmap gradient legend
* update the title shown for the collaborating countries
* update the color for all countries (based on the new scale)
* trigger redraw of countries when we switch into collaboration mode and when the selection of countries changes

**Comment by OmNomNomzzz** [comment]
Note that the logic described applies to both the "mitigation potential" values and the "mitigation cost" values.

**Comment by Quintin-Yu** [comment]
This would be a new feature
