### ISSUE TITLE
Policies section in a case is collapsible in case study pages

### ISSUE THREAD

**Issue by RutgerdeValk** [ConclusionNL/global-mitigation-potential-atlas#62]
-	The policies section in a case is collapsible. Right now, it is open by default, but it might be preferred to have it closed when entering the page, so that the page has more clarity and overview.

**Comment by Quintin-Yu** [comment]
![image](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/36072659/58d4ae4a-dff4-4be4-9ee7-e1477c8cfe9c)
![image](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/36072659/a8a8aa82-814a-4d83-b83e-ad8645f6a989)
Policies section in a case is collapsible and can be opened and closed by clicking on the Policies (TAB)
