### ISSUE TITLE
Support Long Click on Zoom Buttons - use for zoom reset (to 1) and max zoom in

### ISSUE THREAD

**Issue by lucasjellema** [ConclusionNL/global-mitigation-potential-atlas#65]
a fun feature, almost an easter egg. not important.

if the Zoom Out icon is clicked upon for more than 0.5 ? seconds, do a zoom reset to scale factor 1.
(note: d3 does not have long click; you need to work with mouse down and mouse up events)

if the Zoom In icon is clicked upon for more than 0.5 seconds - do a full zoom in (or at least scale by a factor of 3)

**Comment by Quintin-Yu** [comment]
This would be a new feature
