### ISSUE TITLE
Country page feedback

### ISSUE THREAD

**Issue by Quintin-Yu** [ConclusionNL/global-mitigation-potential-atlas#66]
- [x] Remove numbering before sections
- [x] At very end a section should be added that links to cases
- [x] Add subsection under country context to add specific parameters
- [x] Singapore and Indonesie need to have a "Outlook mitigation potential 2035 section" The other 7 don't
- [x] Create a template for all 9 countries
- [x] Add section to add references

**Comment by lucasjellema** [comment]
i think the tabs are not very well recognizable as clickable:


![Image](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/1296324/88cb5a62-d125-4e89-853f-c5eb311bd9ee)

**Comment by lucasjellema** [comment]
i do not understand what this is:
"Add subsection under country context to add specific parameters"

how do I recognize 
"[Add] section to add references"

perhaps you can add images that illustrate what you have done

**Comment by Quintin-Yu** [comment]
- [x] Remove numbering before sections
Headers originally had numbering ex. 1. Country Context. The 1. should be removed.
- [x] At very end a section should be added that links to cases
At the bottom of each page there should be a section for cases.
![image](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/36072659/d93287c5-ba61-45a9-9b88-242abcdf43e7)
- [x] Add subsection under country context to add specific parameters
Request to add a subsection under Country Context. This section is added as a paragraph in the back end and parameters can be added for each country where needed.
![image](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/36072659/93784bd8-a3c4-4426-bc2d-d70f5f468949)
- [x] Singapore and Indonesie need to have a "Outlook mitigation potential 2035 section" The other 7 don't
Singapore and Indonesie have a extra tab on their web-page named Outlook mitigation potential 2035. Screenshot below from Singapore.
![image](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/36072659/2020e3ab-2f86-42fa-b039-7ae1271738ac)
Other countries don't have this tab as there is no data for them. Screenshot below from Philippines.
![image](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/36072659/d8089471-17f5-4b5f-9c7b-a9ba16fdb642)

- [x] Create a template for all 9 countries
The countries that are included in pilot all have the same layout except for two. CA requested all the country pages to have the same template applied to them. This can be checked by looking at all the country pages.
- [x] Add section to add references 
A country page can have references. This section is currently only shown when there is a reference available. So Viet Nam has a reference available as this country has a fake reference.
![image](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/36072659/44037b4d-73f2-4031-97db-caedd36a0941)
