### ISSUE TITLE
Policy page

### ISSUE THREAD

**Issue by Quintin-Yu** [ConclusionNL/global-mitigation-potential-atlas#67]
- [x] Policy inventory tab needs category policy instruments

**Comment by lucasjellema** [comment]
can you illustrate (image) what this is?

**Comment by Quintin-Yu** [comment]
This issue refers to an extra item that should be in the lower part of each policy inventory item. This section is cirkled in red:
![image](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/36072659/08c609d1-6c99-4334-a3bd-82390703e346)
