### ISSUE TITLE
Navigate to cases for specific technology when that technology has been clicked upon in bar chart under stacked area potential mitigation daiagram

### ISSUE THREAD

**Issue by lucasjellema** [ConclusionNL/global-mitigation-potential-atlas#69]
When a bar is clicked, an event is emitted for the specific technology that the bar represents. At this moment, the Atlas should navigate to technology cases for this specific technology. 

![image](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/1296324/3fca7bd4-bda6-4e8a-ba9f-e9481df55476)

The component that presents the bar chart already emits an event for the technology selection. It needs to be consumed and handled, leading to the navigation to (and selection of) cases.

Follow up on #14

**Comment by lucasjellema** [comment]
@Quintin-Yu  can you indicate to what page /URL the navigation should take place? And what is the URL query parameter to use for filtering on the right technology?

**Comment by OmNomNomzzz** [comment]
We do not have enough policies for specific technologies mapped in the pilot phase for this functionality. Do not need this functionality at the pilot phase.
