### ISSUE TITLE
Welcome popup should be displayed only once per session

### ISSUE THREAD

**Issue by lucasjellema** [ConclusionNL/global-mitigation-potential-atlas#70]
Currently, the welcome popup is displayed not just on initial launch of the application, but whenever the user navigates to the world map. For example: after reviewing cases, when the user clicks on the icon in the upper left hand corner, the popup is there (again). I believe it should be shown only once per session.

![image](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/1296324/57e4f5ce-f2bf-4e60-9895-e5121e950e79)

**Comment by lucasjellema** [comment]
using browser sessionStorage to remember that the welcome card already has been shown in the current session (and should not be shown again)

**Comment by Quintin-Yu** [comment]
Pop-up is not shown again unless I close the website and launch it again. Feature seems to be working.
