### ISSUE TITLE
Change units in popup country details window and in toggle box

### ISSUE THREAD

**Issue by lucasjellema** [ConclusionNL/global-mitigation-potential-atlas#71]
These units need to be changed:
![image](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/1296324/21af1770-f4e6-4775-b08d-dc8eebeef282)

Aniq: "The units should be the units in the columns in the csv files.

So in this situation, it should be MtCO2e, and $/tCO2e."

**Comment by lucasjellema** [comment]
It has been implemented :

![image](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/1296324/f8e32766-bdf7-4211-b660-de7fd6beb008)

**Comment by Quintin-Yu** [comment]
Implementation is completed
