### ISSUE TITLE
remove toggle between cost and absolute mitigation potential - and all associated logic - from horizontal level gauge

### ISSUE THREAD

**Issue by lucasjellema** [ConclusionNL/global-mitigation-potential-atlas#77]
The toggle should be taken out - showing the Cost in the gauge is no longer supported. Note: instead of the current toggle, Aniq would like to have  a radio group to switch between to have radio buttons or a drop down menu for 0/50/100/200. This will be another issue. However, do not completely upset the styling yet 

![image](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/1296324/002f8588-0846-4532-b6c6-f85d68e339d8)

**Comment by lucasjellema** [comment]
![image](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/1296324/8da5e7d7-5bf1-40bd-bb33-20322bbad665)

**Comment by OmNomNomzzz** [comment]
The toggle has been taken out. The issue has been resolved.
