### ISSUE TITLE
add radiogroup and logic to switch mitigation potential between  0/50/100/200 in horizontal gauge 

### ISSUE THREAD

**Issue by lucasjellema** [ConclusionNL/global-mitigation-potential-atlas#78]
in #77  the toggle between cost and mitigation potential is removed.

Aniq desired to have radio buttons or a drop down menu for 0/50/100/200 . when the user changes the selection, the gauge should be updated with the value at 0/50/100 and 200. The title should likewise be updated.
![image](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/1296324/1b0545d6-8263-48d6-9813-3d56faf9efb1)

**Comment by lucasjellema** [comment]
Made first steps.

Radiogroup needs styling
The gauge must be reimplemented . Starting with the outline and a blue fill . Then apply orange on top of that.

**Comment by lucasjellema** [comment]
I think this is done:
![image](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/1296324/808d3299-2f15-4720-96cf-6114b30af724)

**Comment by OmNomNomzzz** [comment]
Radio buttons work for gauge. The feature has been implemented properly.
