### ISSUE TITLE
Replace option Mitigation Cost ($/tCO2e) in world map toggle and country details popup with potential at 0

### ISSUE THREAD

**Issue by lucasjellema** [ConclusionNL/global-mitigation-potential-atlas#79]
Please replace the “mitigation cost” with “mitigation potential at 0”.
![image](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/1296324/d949a70d-3bf4-4519-b16c-112486d33d35)

![image](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/1296324/966de7ff-534f-4a7c-a67e-27469f33b93d)

**Comment by lucasjellema** [comment]
![image](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/1296324/92abe89f-da37-41d4-ba07-e7d11db722d1)
it has been implemented

**Comment by OmNomNomzzz** [comment]
The changes look good. 

However, the Maximum Mitigation potential (top row) seems to not be working on the website right now. Is this a data issue on  my side?

![image](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/23158406/f308693a-1e45-4957-bd62-fa8844e47c19)

**Comment by OmNomNomzzz** [comment]
Issue has been resolved. Cost has been replaced by Mitigation Potential.
