### ISSUE TITLE
Only use At Average values from file heatmaps_collaboration.csv 

### ISSUE THREAD

**Issue by lucasjellema** [ConclusionNL/global-mitigation-potential-atlas#80]
we should be using the “at average” values from file heatmaps_collaboration.csv . The other values that were marginal do not make sense/ are not as useful. 

![image](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/1296324/971ac0ca-8b19-4777-b857-aa8cb83caf4c)

**Comment by OmNomNomzzz** [comment]
This issue has been resolved. Website now only uses average values.
