### ISSUE TITLE
Add option "Country-Name Detailed National Modelling" based on total_data.csv to Stacked Area Chart page

### ISSUE THREAD

**Issue by lucasjellema** [ConclusionNL/global-mitigation-potential-atlas#81]
The Stacked Area Page should offer an extra option for every country - both when multiple countries are selected or when a single country is selected:  the option "Country-Name Detailed National Modelling" next to the regular Country option. The data for the chart when this option is selected comes from file total_data.csv

![image](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/1296324/e21f7a90-23e8-4568-b386-f818c074624c)

**Comment by lucasjellema** [comment]
comment by @OmNomNomzzz :

> Please represent it similar to how it is now, from a drop down menu. Yes, for three countries that would be 2+3*2=8. For four countries it would be 2+4*2=10. For two countries it would be 2+2*2=6. However, for just one country it would be 0+2=2; no collaboration data, only country data.
> Yes, the option for a detailed country should be called: “Country-Name Detailed National Modelling”, so e.g. “Singapore Detailed National Modelling”

**Comment by lucasjellema** [comment]
Done


![Image](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/1296324/f1a75803-d223-4e89-aec4-a069a2b39b0b)

**Comment by OmNomNomzzz** [comment]
I can now see the plots for the "Detailed National Modelling". This issue has been resolved.
