### ISSUE TITLE
Methodology page template

### ISSUE THREAD

**Issue by RutgerdeValk** [ConclusionNL/global-mitigation-potential-atlas#84]
Methodology page should have a template uploaded so that sections can be hidden etc.  (Same type of thing as country pages have, but different template).

Template:
https://app.box.com/file/1330253879798

**Comment by Quintin-Yu** [comment]
![image](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/36072659/4f4ae2ee-531b-4a17-b295-ad2962a53ad9)
![image](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/36072659/9c788921-5acb-497c-bcd5-547e21769ada)
Sections are also collapsible based on request:
![image](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/36072659/17bfef15-64ed-48a2-92a5-74a9afb40ed2)

Review needed

**Comment by RutgerdeValk** [comment]
Looks great Quintin, I'll close this issue.

**Comment by noni-12** [comment]
Please add side margin the page and if possible please add the sections within a case like how they are in the policies page and cases page

**Comment by Quintin-Yu** [comment]
@noni-12 Side margins have been added and the sections are now in a card layout
![image](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/36072659/b7f42538-6f04-4cdb-a498-a46699ee36b5)

In the future please make a new GitHub issue for this. Instead of opening an old issue. I only noticed that this one was reopened by chance.

Review of this feature is needed

**Comment by noni-12** [comment]
Will  (expandable) be visible in the final product?

**Comment by Quintin-Yu** [comment]
Added it to make it clear to the users you can click on the sections, if you want it removed then I will do so

**Comment by noni-12** [comment]
It would be good to remove them, no?

**Comment by Quintin-Yu** [comment]
Alright I'll remove it in that case

**Comment by Quintin-Yu** [comment]
![image](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/36072659/86e23bfd-6dea-46b0-8f9a-d0c9a0004901)
Expandable has been removed

**Comment by noni-12** [comment]
All good, many thanks
