### ISSUE TITLE
Change color of countries that are not part of the study.

### ISSUE THREAD

**Issue by OmNomNomzzz** [ConclusionNL/global-mitigation-potential-atlas#87]
Currently, the color of countries not part of the study is similar to having a low mitigation potential value. So it is difficult to distinguish which countries are and are not in the study.

Change the colour of other countries to a much darker gray/ black so that it is more obvious.

**Comment by lucasjellema** [comment]
@OmNomNomzzz 

Countries for which there is no data in the file heatmap_collaboration.csv are all treated the same: grayed out.
You are making a distinction it seems between "in the heatmap data file" and "in the study". Do you have a list of (two letter country codes of) the countries in the study (or at least the countries that are not in the heatmap csv file and are in the study and should be identifiable by color as in the study?

What is the value of a country being in the study if we cannot assign a color to it in the heatmap and do not allow users to select it?

**Comment by OmNomNomzzz** [comment]
No, I am not trying to make a distinction. When I say "countries not in the study", I actually mean"countries not in the heatmap file". They are the same. Sorry for the confusion.

If countries do not exist in the heatmap file, they are currently grayed out. But the gray colour is similar to a colour in the typical heatmap. So recommend to switch to a darker gray, no change in logic, just change colour.

**Comment by lucasjellema** [comment]
I am a bit afraid that the presentation will suffer from too dark a color. What do you think of this?
![image](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/1296324/545f5c2e-248a-4f77-bc5f-379af764caef)
can you propose a specific gray-shade that you feel is appropriate?

**Comment by OmNomNomzzz** [comment]
This colour brownish colour is good. It looks sufficiently different from the countries for which we have data. This issue is resolved.
