### ISSUE TITLE
Need to scroll when using the map

### ISSUE THREAD

**Issue by OmNomNomzzz** [ConclusionNL/global-mitigation-potential-atlas#88]
Website functions strange when opened from a browser on 1080p screen, it looks ok on a 1440p screen. The pop-up when you click a country gets moved to bottom of screen and you need to scroll to see part of the pop-up. The heatmap legend/scale also gets cut off for some users.

Users sometimes need to scroll on the page just to see the map or the pop-up. But scrolling zooms in-out of map if the mouse is on the map, but scrolls the webpage when the mouse is not hovering over the map. It making using the map very inconvenient. Can contact Aniq for more details.

**Comment by lucasjellema** [comment]
what is the minimum screensize that you want to have supported? @OmNomNomzzz 
(if the browser window is too small, we simply cannot show all the elements we have at present)

**Comment by OmNomNomzzz** [comment]
1080p is what I want to support.

![image](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/23158406/cb23c6ad-0469-45c2-bbad-3486853eb864)

This is what I currently see on my screen. I need to scroll down to see the dynamic bar charts.

**Comment by lucasjellema** [comment]
note: trelated tpo #34

**Comment by OmNomNomzzz** [comment]
I have found out why this issue arises. If we set the "scale of size text and other items" in windows display setting to value higher than 100%, then we start seeing UI issues. E.g. the default in my laptop is 125%.
![image](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/23158406/014838a0-7808-4be9-a81b-944785871992)
 This results in the heatmap being cut out and me needing to scroll to just see the map.
![image](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/23158406/ff265290-db7b-45c4-b3b0-42df7625a9f8)
![image](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/23158406/7752694e-647c-43bb-984b-bd21ca6f5c8c)

However, after setting it back to 100% and refreshing the browser. Everything looks ok.

![image](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/23158406/8a62f9dc-bd13-48f9-aad4-19b1d0cf4c1e)

![image](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/23158406/cefdc3bd-24bc-45e8-afc4-98ae353e6f33)

I do not know if this is something the team can fix. It it is out of your hands, we can leave it.

**Comment by lucasjellema** [comment]
I have implemented some improvements for using the map on smaller window sizes. Location and size of popups for example. I still need to adjust the size of the heatmap legend (I believe it now scales too small for a small window size)

![image](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/1296324/b1870116-a82f-4098-94b3-3c7642034a42)
I probably have to refine the location of the zoom buttons.
And adjust the focus of the zoom when country is clicked - it currently is too high with regards to the togglebox:
![image](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/1296324/9e8d3081-e2f9-4f14-9609-1596c00a7a19)

**Comment by lucasjellema** [comment]
I believe the last changes have resolved this issue. When the window size changes, the size of the worldmap is immediately changed as well. for smaller browser windows, some elements will be smaller (smaller font, smaller width, different location). 
![image](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/1296324/65ef1c03-08a5-4cba-a6dc-7e82a3e2e116)

Please let me know in a new ticket if any additional specific changes are required

**Comment by OmNomNomzzz** [comment]
The current issue is resolved. I will send a new ticket if there are other issues.
