### ISSUE TITLE
Make Mitigation Potential Diagram Pop-up Bigger

### ISSUE THREAD

**Issue by OmNomNomzzz** [ConclusionNL/global-mitigation-potential-atlas#89]
On a 1080p screen, the mitigation potential diagram (dynamic curve) seems to not fit in the pop-up. So users need to scroll on the pop-up to see both the stacked chart and corresponding bar chart. Users should be able to see both the stacked chart and the bar chart together so that when they move the slider, they can see the corresponding changes immediately. The pop-up window seems to be a small fraction of the screen, and the stacked chart is very big. Maybe we could make the pop-up window bigger so that it takes up more of the screen, and also make the graphs themselves smaller so that both the stacked and bar charts can fit on the screen at the same time.

**Comment by lucasjellema** [comment]
could you add a screenshot to illustrate the statement "The pop-up window seems to be a small fraction of the screen" - I do not recognize this situation. @OmNomNomzzz 

we can easily make the stacked area chart smaller and thereby bring up the bar chart. 

what is the minimum browser window size we should cater for?

**Comment by lucasjellema** [comment]
related to #34  and #88

**Comment by lucasjellema** [comment]
I have made the stacked area chart a bit smaller
and I have applied a scale factor that will further reduce the size of the charts depending on the size of the browser window: for a smaller window, the charts are proportionally smaller. 


![Image](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/1296324/010d58f9-a6f6-4018-ad52-bb2c39329ff9)

Can you verify if that resolves this issue?

I have not yet built in a direct reaction to a change of the browser window while it is already showing the diagram. That could be done but seemed overdone for now.

**Comment by OmNomNomzzz** [comment]
I still seem to be having the same issues.

![image](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/23158406/d6aa22a3-76ae-425c-8e8d-4fa503e3924a)

Is my browser just not refreshed?

**Comment by lucasjellema** [comment]
Can you try again at https://app-gmpa-t.azurewebsites.net/ ?
You may have to use force refresh of the browser (CTRL + F5 on a Windows machine) or perhaps open in a new, incognito browser window (CTRL+Shift+N on a Windows computer)

Here is what I can see:
![image](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/1296324/f80b9f0c-c5d1-4526-b8ad-31403153fabb)

**Comment by OmNomNomzzz** [comment]
clt+f5 worked. The pop-up looks much better now. This issue has been resolved.
