### ISSUE TITLE
Change Radio Buttons Label

### ISSUE THREAD

**Issue by OmNomNomzzz** [ConclusionNL/global-mitigation-potential-atlas#90]
Change the radio buttons for mitigation potential so that the first line does not have a button but says
"Annual Mitigation Potential (MtCO2e) at Average Abatement Cost of:" 
The other buttons should then say "No Cost Limit", "0 $/tCO2e", "50 $/tCO2e", etc

![image](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/23158406/901b7e56-e430-4b3f-b1ec-31308e8f27c0)

The same should be done for the radio buttons on the pop-up.
![image](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/23158406/0bf72aa6-48b7-4cd0-9bc0-209385434158)

**Comment by OmNomNomzzz** [comment]
"Annual Mitigation Potential (MtCO2e) at Average Abatement Cost of:"
The other buttons should then say:
0 $/tCO2e
50 $/tCO2e
100 $/tCO2e
200 $/tCO2e
No cost limit

**Comment by OmNomNomzzz** [comment]
Please also note that the order of the buttons have been changed. Place the ``No cost limit'' value to the bottom. No cost limit is the mitigation potential without any cost associated.

**Comment by lucasjellema** [comment]
Initial implementation looks like this:
![image](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/1296324/fbcc37f8-67c1-47d4-acaf-bf06b266bb83)
what should be the selected value when the user first opens the map? WHich of the radio buttons should be the active one?

**Comment by lucasjellema** [comment]
for the collaboration benefits:
![image](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/1296324/b8e06cfa-9b7d-4802-8896-0da8fd47a6ed)

**Comment by OmNomNomzzz** [comment]
These both look good!

**Comment by OmNomNomzzz** [comment]
The "No Cost Limit" radio button should be active by default.

**Comment by OmNomNomzzz** [comment]
Everything looks well. This issue has been resolved.
