### ISSUE TITLE
Remove "None" from the heatmap radio button

### ISSUE THREAD

**Issue by OmNomNomzzz** [ConclusionNL/global-mitigation-potential-atlas#91]
Heatmap should load with "Maximum Potential", currently called "Mitigation Potential (MtCO2e)". Remove the "none" 
button as it makes it confusing when new users first load the page.

![image](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/23158406/e64ebf07-f9be-41de-ac51-968548a688ed)

**Comment by lucasjellema** [comment]
Implemented:
![image](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/1296324/e4b6f8f5-b713-44f8-b1ac-ff19cb395066)

**Comment by OmNomNomzzz** [comment]
Issue sorted. Followed up with Issue #90.
