### ISSUE TITLE
Axes labels for graphs

### ISSUE THREAD

**Issue by OmNomNomzzz** [ConclusionNL/global-mitigation-potential-atlas#92]
In the Cost vs Emissions graphs for the country pop-up, collaboration pop-up, and dynamic "Mitigation Potential Diagram" 
pop-up: Change y-axes to "Annualized System Costs (Billion $)". Change x-axes to "Annual System Emissions (MtCO2e)".

![image](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/23158406/1015c9c7-51d3-4d33-ba45-3d8e27cbd8b0)

![image](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/23158406/e640fb80-e3b7-4810-874b-27cac01c9b4e)

![image](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/23158406/8acff18e-453f-491b-8d28-a24a51207844)

**Comment by lucasjellema** [comment]
initial implementation is done:
![image](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/1296324/36374085-ccb1-48ca-9924-3219c35f3038)

Question: @OmNomNomzzz  the title for the y axis is too long for the current font size/ diagram size. How to resolve this?
* shorter title
* smaller font size
* two lines of title text
* ...

**Comment by OmNomNomzzz** [comment]
two lines of title text if possible.

If it is a lot of effort to add two lines: shorten to "Annualized System Costs(Bil $)" and smaller font.

**Comment by lucasjellema** [comment]
like this:


![Image](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/1296324/9dc71916-726f-4c36-be10-9051bf493cbd)

**Comment by OmNomNomzzz** [comment]
Yes this works.

**Comment by Quintin-Yu** [comment]
Feature is completed as expected
