### ISSUE TITLE
Update title for Mitigation Potential Diagram

### ISSUE THREAD

**Issue by OmNomNomzzz** [ConclusionNL/global-mitigation-potential-atlas#93]
For the STEVFNs models (i.e. from total_data_autarky.csv and total_data_collaboration.csv).
Change the title from "Country(ies)'s Mitigation Potential Diagram 2030/2050" to:

"Country(ies)'s Mitigation Potential Diagram for 2050:
This uses a generalized STEVFNs model that better captures the challenges and benefits of international collaboration. This is translated from potentially different detailed national-level models used by respective countries. Emissions and costs are annualized for a 30 year greenfield project built in 2050. System meets 2050 demand for power and high temperature industrial heating sectors. "

It is ok for it to go across multiple lines.

![image](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/23158406/3cc624d7-25f6-46e3-86ab-32a8403cc209)

For OSeMOSYS models (i.e. from total_data.csv).
Change the title from "Country(ies)'s Mitigation Potential Diagram 2030/2050" to:

"Country(ies)'s Mitigation Potential Diagram for 2050:
This uses a detailed national-level model that represents the current model and data being used by the country. This is used to calibrate the STEVFNs model used to model international collaboration. The system meets 2015-2070 demand for power, industry and transport sectors. The costs are the NPV costs for a brownfield project from 2015-2070. The emissions are 2050 emissions assuming a linear reduction from 2025-2050, and constant emissions from 2050-2070. "

It is ok for it to go across multiple lines.

**Comment by lucasjellema** [comment]
@OmNomNomzzz 
should all that text be displayed in the same (large) font? Or a distinction between 
"Country(ies)'s Mitigation Potential Diagram for 2050: 
in large font 
and the explanation in smaller font?

**Comment by OmNomNomzzz** [comment]
The latter.
"Country(ies)'s Mitigation Potential Diagram for 2050"
should be displayed in large font.
explanation in smaller font. Thank you

**Comment by lucasjellema** [comment]
What about this?
![image](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/1296324/42a1ee6f-a709-4e1f-8e43-3e173884ef6d)
is this what you are looking for?

**Comment by OmNomNomzzz** [comment]
This is better than what I was looking for.
