### ISSUE TITLE
Allow users to inspect/download the raw datafiles used for the visualizations 

### ISSUE THREAD

**Issue by lucasjellema** [ConclusionNL/global-mitigation-potential-atlas#95]
Add this feature:
for users to have access to the raw data values underpinning the charts in the GMPA. For example make it possible to download the raw files (csv files) using a special key combination (easter egg - style) when the mouse hovers over a chart.

For CA team to inspect if the proper files are used, for third parties to verify/understand/validate how you produced the charts.  

Aniq indicated "Actually that would be really good! I didn't realise this was something that could be done.

I initially wanted to just host the input data files for the model on my GitHub. But being able to just download the data for the charts would be very useful!

Agreed, this is good for both troubleshooting and for transparency."

**Comment by OmNomNomzzz** [comment]
Seems to be implemented for heatmap, line chart, and stacked chart properly. 

Download starts when mouse over press clt+shift+u.

One issue, it seems to be starting my "read aloud" in microsoft edge haha Fine otherwise.

**Comment by lucasjellema** [comment]
I have picked CTRL+Shift+U. If that combination has another function (too), then both will be activated. If you want, I can use a different key combination. Just let me know which.

**Comment by lucasjellema** [comment]
It should now also work for the worldmap (heatmap data file).  Please review and close issue when you are satisfied

**Comment by OmNomNomzzz** [comment]
CLTR+Shift+U works. I am satisfied with the results.
