### ISSUE TITLE
'About the GMPA’ in Umbraco

### ISSUE THREAD

**Issue by noni-12** [ConclusionNL/global-mitigation-potential-atlas#96]
the Body Text box should have the same editing functionality of the body text box on the ‘GMPA-Methodology’ page, including the ability to add pictures and links
![GMPA-Methodology](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/150308465/851ff6d8-9078-4881-b2e5-3c9514abbb68)
![AboutUs](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/150308465/3cc4e327-1d1d-42f2-8be7-5b4a02b641bb)

**Comment by Quintin-Yu** [comment]
Issue should be resolved. Please have a look at Umbraco to see if this has been correctly handeled.
![image](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/36072659/c62231af-d929-436d-a097-596d3c133ed3)

Review is now needed

**Comment by noni-12** [comment]
Working fine, thanks
