### ISSUE TITLE
Case study page

### ISSUE THREAD

**Issue by noni-12** [ConclusionNL/global-mitigation-potential-atlas#97]
Please consider adding the case study filtering option to the sidebar on the specific case study page also. Currently, when users are on a case study page, they have to navigate back to the home page to browse other case studies. 
![Screenshot 2023-11-17 at 12 50 24 pm](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/150308465/6ee30d46-7f4a-456e-aa07-6fdca1a66daa)
![Screenshot 2023-11-17 at 12 50 11 pm](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/150308465/00c6fcf3-8f56-415d-af2c-fa2c66087296)

**Comment by Quintin-Yu** [comment]
Added a return to previous page link in the top left of the page, as well as to other pages where is is logical.

Country:
![image](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/36072659/4cc6387d-25e8-4246-876b-cc847b7fef19)

Policies:
![image](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/36072659/67d3c642-4df9-4f7c-9b42-2222eba9bb1a)

Cases:
![image](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/36072659/6986ee9f-ac55-4fec-b9be-27c08f51665c)

Case:
![image](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/36072659/be8166ef-2d19-4230-8dae-3e472c9351f5)

Changes are visible on: https://app-gmpa-t.azurewebsites.net/

**Comment by noni-12** [comment]
Yes, it is fine
